import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://127.0.0.1:8000',D:Record<string,string>={first_name:'Aarav',last_name:'Sharma',full_name:'Aarav Sharma',email:'aarav@example.com',phone:'+91 9876543210',institution:'Example Institute of Technology',degree:'B.Tech',branch:'Computer Science',cgpa:'8.14',skills:'React, TypeScript, Python, FastAPI',projects:'SmartForm context-aware filling system'};
const G:Record<string,string[]>={'Personal vault':['first_name','middle_name','last_name','full_name','email','phone','address','city','state','country','pin_code'],Academic:['institution','degree','branch','cgpa','roll_number','enrollment_number','passing_year'],Projects:['projects','skills','github','linkedin','portfolio'],Resumes:['resume_sde','resume_ai_ml','resume_general'],Documents:['certificate_notes','documents'],'Privacy & security':[]},P=['Overview',...Object.keys(G),'AI settings','History'];
function App(){const[page,setPage]=useState('Overview'),[v,setV]=useState(D),[s,setS]=useState(''),[status,setStatus]=useState('Connecting…'),[note,setNote]=useState(''),[hist,setHist]=useState<any[]>([]),[ai,setAi]=useState<any>({api_key:'',model:'nvidia/nemotron-3-super-120b-a12b',base_url:'https://integrate.api.nvidia.com/v1'});const call=async(p:string,i?:RequestInit)=>{let r=await fetch(API+p,i);if(!r.ok)throw Error((await r.json()).detail);return r.json()};
useEffect(()=>{call('/profile').then(x=>{if(Object.keys(x.values).length)setV(a=>({...a,...x.values}));setS((x.sensitive_keys||[]).join(', '));setStatus('Local agent connected')}).catch(()=>setStatus('Local agent offline'));call('/settings/ai').then(setAi).catch(()=>{})},[]);useEffect(()=>{if(page==='History')call('/history').then(setHist).catch(()=>setNote('Start the local agent to view history'))},[page]);
const save=async()=>{try{await call('/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:v,sensitive_keys:s.split(',').map(x=>x.trim()).filter(Boolean)})});setNote('Vault saved locally and encrypted.')}catch(e:any){setNote(e.message)}};const saveAi=async()=>{try{let x=await call('/settings/ai',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(ai)});setAi({...ai,api_key:'',api_key_configured:x.api_key_configured});setNote('AI key saved encrypted locally.')}catch(e:any){setNote(e.message)}};
let body:React.ReactNode;if(page==='Overview')body=<><div className="hero"><span className="eyebrow">SMARTFORM CONTROL CENTER</span><h1>Your applications, under your control.</h1><p>Complete your vault, configure NVIDIA AI when needed, and review every extension change before submission.</p><button className="primary" onClick={()=>setPage('Personal vault')}>Complete profile</button></div><div className="stats"><article><b>{Object.values(v).filter(Boolean).length}</b><span>vault values</span></article><article><b>{ai.api_key_configured?'Ready':'Local only'}</b><span>AI status</span></article><article><b>Manual</b><span>submission</span></article></div></>;
else if(page==='AI settings')body=<article><span className="eyebrow">NVIDIA NEMOTRON</span><h1>AI settings</h1><p>AI runs only after AI Fill. The key is encrypted in local storage and never exposed to websites or the extension.</p><label>NVIDIA API key <small>{ai.api_key_configured?`Configured (${ai.api_key_masked||'hidden'})`:'Not configured'}</small><input type="password" value={ai.api_key||''} onChange={e=>setAi({...ai,api_key:e.target.value})} placeholder="Paste key to set or replace"/></label><label>Model<input value={ai.model||''} onChange={e=>setAi({...ai,model:e.target.value})}/></label><label>Base URL<input value={ai.base_url||''} onChange={e=>setAi({...ai,base_url:e.target.value})}/></label><button className="primary" onClick={saveAi}>Save AI settings</button></article>;
else if(page==='History')body=<article><h1>Application history</h1><p>Only domains, timestamps and counts are kept—never form answers.</p><button onClick={async()=>{await call('/history',{method:'DELETE'});setHist([])}}>Clear local history</button><div className="history">{hist.length?hist.map(x=><div key={x.id}><b>{x.domain}</b><span>{new Date(x.created_at).toLocaleString()} · {x.fields} fields · {x.ai_fields} AI</span></div>):<p>No forms processed yet.</p>}</div></article>;
else{let keys=G[page]||[];body=<article><span className="eyebrow">{page.toUpperCase()}</span><h1>{page}</h1><p>Add information SmartForm can use for direct filling. Empty values are skipped.</p><div className="fields">{keys.map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={v[k]||''} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}</div>{(page==='Personal vault'||page==='Privacy & security')&&<label>Sensitive keys <small>Comma-separated and excluded from AI.</small><input value={s} onChange={e=>setS(e.target.value)} placeholder="aadhaar, passport_number"/></label>}<button className="primary" onClick={save}>Save {page}</button></article>}
return <main><aside><div className="brand">✦ SmartForm</div><p>Context-aware filling</p>{P.map(x=><button key={x} className={page===x?'active':''} onClick={()=>setPage(x)}>{x}</button>)}</aside><section><header><div><span className="eyebrow">LOCAL-FIRST FORM ASSISTANT</span><h2>{page}</h2></div><div className={status.includes('offline')?'status offline':'status'}>● {status}</div></header>{note&&<div className="notice">{note}<button onClick={()=>setNote('')}>×</button></div>}{body}</section></main>};createRoot(document.getElementById('root')!).render(<App/>);
